#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <input_file>"
    exit 1
fi

input_file="$1"

if [ ! -f "$input_file" ]; then
    echo "Input file does not exist."
    exit 1
fi

awk 'NR % 2 == 1' "$input_file"
