#!/bin/bash

# List local variables
echo "Local Variables:"
set | grep -o '^[a-zA-Z_][a-zA-Z_0-9]*='

# List environment variables
echo -e "\nEnvironment Variables:"
printenv

# List functions
echo -e "\nFunctions:"
declare -F | awk '{print $3}'
